/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.esm.core;

import ua.com.numbers.StringUtils;

import java.util.Arrays;

/**
 * The Utils class provides utility methods for working with arrays of strings.
 */
final public class Utils {
    /**
     * Private constructor to prevent instantiation of the class.
     */
    private Utils() {
    }

    /**
     * Checks if all elements of the specified string array represent positive numbers.
     *
     * @param array the string array to check
     * @return true if all elements of the array represent positive numbers, false otherwise
     */
    public static boolean isAllPositiveNumbers(final String... array) {
        return array != null && array.length != 0 && Arrays.stream(array)
                .allMatch(StringUtils::isPositiveNumber);
    }
}
