name: Java CI with Maven(Gift-shop)

on:
  push:
    branches: [ module#3 ]
  pull_request:
    branches: [ module#3 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml

      - name: Ip
        run: ip address

      - name: find file
        run: find . -name api-1.0.0.jar