name: Java CI with Maven

on:
  push:
    branches: [ "module#3" ]
  pull_request:
    branches: [ "module#3" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'zulu'
          cache: maven
      - name: cd
        run: cd .\zero\Module#04

      - name: Build with Maven
        run: mvn clean package -DskipTests
