/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.esm.api;

import com.epam.esm.core.Utils;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 * The `App` class represents the main class of the application.
 * It contains a static `main` method that is called when the application is started.
 */
final class App {
    /**
     * A private static `Logger` instance used for logging messages.
     */
    private static final Logger logger = Logger.getLogger(App.class.getName());

    /**
     * Private constructor to prevent instantiation of the `App` class.
     */
    private App() {
    }

    /**
     * The main method that is called when the application is started.
     * It invokes the `Utils.isAllPositiveNumbers` method to check if all the input arguments are positive numbers.
     *
     * @param args The command-line arguments passed to the application.
     */
    public static void main(final String[] args) {

        boolean result = Utils.isAllPositiveNumbers("12", "79");
        logger.log(Level.INFO, "All positive numbers are {0} ", result);
    }
}

