name: Java install openjdk-8-jdk

on:
  push:
    branches: [ module#2 ]
  pull_request:
    branches: [ module#2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven

      - name: sudo apt-get update
        run: sudo apt-get update

      - name: package file
        run: mvn -B package --file pom.xml

      - name: check path
        run: ls -la && pwd

      - name: find Tomcat
        run: find . -name gift.war

      - name: run java
        run: java -jar ./api/target/gift.war
