/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.epam.esm;

import static org.apache.commons.lang3.StringUtils.isNumeric;

/**
 * A utility class for string manipulation.
 */
final public class StringUtils {
    /**
     * Private constructor to prevent instantiation.
     */
    private StringUtils() {
    }

    /**
     * Determines whether the specified string represents a positive number.
     *
     * @param string the string to check
     * @return {@code true} if the specified string represents a positive number, {@code false} otherwise
     */
    public static boolean isPositiveNumber(final String string) {
        return isNumeric(string) && Integer.parseInt(string) > 0;
    }
}
